CSharpCollections1
LazarevaAleksandra/home_work_2 pull request #8
Opened 2022-11-08 15:22 UTC by LazarevaAleksandra

2022-11-13 20:13 UTC, MariaEroshevich requested changes

2022-11-13 20:13 UTC, MariaEroshevich commented on homework/homework.sln
> +<<<<<<< HEAD
don't you have problems with the build project?

2022-11-13 20:13 UTC, MariaEroshevich commented on homework/CSharpCollections1/Program.cs
> +//using System.Collections.Generic;
You don't implement "It is required to compile a new list of voters living at a given address in alphabetical order.".
You should create new list with Citizens who live at the given address (the same address for citizens).

2022-11-13 20:13 UTC, MariaEroshevich commented on homework/CSharpCollections1/Program.cs
> +//var countrySwap = country.ToDictionary(x => x.Value, x => x.Key).ToList();
does not need to add ToList()

2022-11-13 20:20 UTC, LazarevaAleksandra commented on homework/homework.sln
> +<<<<<<< HEAD
No. Everything is fine. Conflict resolved.

2022-11-18 20:42 UTC, MariaEroshevich requested changes

2022-11-18 20:42 UTC, MariaEroshevich commented on homework/CSharpCollections1/Program.cs
> +newList.Sort((a, b) => a.Street.CompareTo(b.Name));
Still not implemented the previous comment. You should create the separate method where you should pass the address(method with variable) and using FindAll method return new list with citizens, who live at the address you passed to the method and then sort the new list by name.

2022-11-19 13:35 UTC, MariaEroshevich approved these changes

2022-11-20 10:55 UTC, merged